// Add the remaining pages (84–91) here in the same format. [n] marks footnote n.
const PAGES=[
{n:82,title:`Nobel Lecture — Mother Teresa`,paras:[
{t:`About the Author : Mother Teresa (1910-1997) was a Roman Catholic nun and missionary globally revered for her selfless service to the poor and destitute. Born as Anjezë Gonxhe Bojaxhiu in Skopje (now in North Macedonia), she felt a divine calling to serve humanity and moved to India in 1929. In 1950, she founded the Missionaries of Charity in Kolkata, an organization dedicated to helping the “poorest of the poor.” Her tireless work earned her worldwide recognition, including the Nobel Peace Prize in 1979. A symbol of compassion and humility, she was canonized as Saint Teresa of Calcutta by Pope Francis in 2016. Mother Teresa remains an enduring icon of love, faith, and service.`,bn:`মাদার টেরেসা (১৯১০–১৯৯৭) ১৯২৯ সালে ভারতে আসেন, ১৯৫০ সালে কলকাতায় মিশনারিজ অফ চ্যারিটি প্রতিষ্ঠা করেন এবং ১৯৭৯ সালে নোবেল শান্তি পুরস্কার পান। ২০১৬ সালে তিনি সন্ত ঘোষিত হন।`,k:`Textual fact / Historical context`},
{t:`About the Text : In her Nobel Peace Prize acceptance speech, Mother Teresa delivered a message of love, peace, and the importance of small acts of kindness. She emphasized that true peace begins with family love and highlighted the dangers of poverty, neglect, and abortion, terming them as the greatest destroyers of peace. She quoted Jesus Christ, “Love one another as I have loved you,” and urged people to perform simple acts of love daily. Referencing her work with the dying and suffering, she shared stories of finding dignity in every human life. The speech reflected her deep spirituality, invoking prayers like the "Prayer of St. Francis of Assisi" and stressing faith in action. It remains a timeless plea for compassion and care.`,bn:`এই ভাষণে তিনি ভালোবাসা, শান্তি ও ছোট ছোট দয়ার কাজের কথা বলেছেন। তাঁর মতে সত্যিকারের শান্তি শুরু হয় পরিবারের ভালোবাসা থেকে। (এটি তাঁর ধর্মীয় ও নৈতিক দৃষ্টিভঙ্গি।)`,k:`Textual viewpoint`}]},
{n:83,title:`NOBEL LECTURE`,paras:[
{t:`As we have gathered here together to thank God for the Nobel Peace Prize I think it will be beautiful that we pray the prayer of St. Francis of Assisi[1] which always surprises me very much - we pray this prayer every day after Holy Communion[2], because it is very fitting for each one of us, and I always wonder that 4-500 years ago as St. Francis of Assisi composed this prayer that they had the same difficulties that we have today, as we compose this prayer that fits very nicely for us also. I think some of you already have got it - so we will pray together.`,bn:`নোবেল শান্তি পুরস্কারের জন্য ঈশ্বরকে ধন্যবাদ জানাতে সমবেত হয়ে তিনি সবাইকে নিয়ে সেন্ট ফ্রান্সিসের প্রার্থনা করতে চান। এই প্রার্থনা তাঁরা প্রতিদিন করেন, আর বহু শতাব্দী আগের প্রার্থনা আজকের সমস্যার সঙ্গেও মিলে যায় দেখে তিনি অবাক হন।`,k:`Main idea: opening with prayer`},
{t:`Let us thank God for the opportunity that we all have together today, for this gift of peace that reminds us that we have been created to live that peace, and Jesus[3] became man to bring that good news to the poor. He being God became man in all things like us except sin, and he proclaimed very clearly that he had come to give the good news. The news was peace to all of good will and this is something that we all want - the peace of heart - and God loved the world so much that he gave his son - it was a giving - it is as much as if to say it hurt God to give, because he loved the world so much that he gave his son, and he gave him to Virgin Mary[4], and what did she do with him?`,bn:`তিনি বলেন, শান্তি ঈশ্বরের উপহার; যিশু গরিবদের কাছে সুসংবাদ আনতে মানুষ হয়ে এসেছেন। সেই সুসংবাদ হলো সদিচ্ছাসম্পন্ন সবার জন্য শান্তি। (ধর্মীয় বিশ্বাস)`,k:`Religious viewpoint`},
{t:`As soon as he came in her life — immediately she went in haste to give that good news, and as she came into the house of her cousin, the child - the unborn child - the child in the womb of Elizabeth[5], leapt with joy. He was that little unborn child, was the first messenger of peace. He recognised the Prince of Peace, he recognised that Christ has come to bring the good news for you and for me. And as if that was not enough - it was not enough to become a man - he died on the cross to show that greater love, and he died for you and for me and for that leper and for that man dying of hunger and that naked person lying in the street not only of Calcutta, but of Africa, and New York, and London, and Oslo - and insisted that we love one another as he loves each one of us. And we read that in`,bn:`(পাতা ৮৪-তে চলবে) মেরি তাড়াতাড়ি সুসংবাদ ছড়াতে গেলেন; এলিজাবেথের গর্ভের শিশুটি আনন্দে লাফিয়ে উঠল। তিনি বলেন, যিশু সবার জন্য প্রাণ দিয়েছেন এবং পরস্পরকে ভালোবাসতে বলেছেন।`,k:`Religious viewpoint`}]}
];
const NOTES={1:[`St. Francis of Assisi`,`Patron saint of animals and ecology; known for his prayer, "Make me a channel of your peace".`],2:[`Holy Communion`,`Eucharist; 'The Last Supper', where Christ gave his disciples bread and wine.`],3:[`Jesus`,`Also called Christ of Nazareth. Christians believe him to be the son of God, saviour and preacher of love, compassion and redemption.`],4:[`Virgin Mary`,`Mother of Jesus Christ.`],5:[`Elizabeth`,`A relative of Mary, and mother of John - The Baptist.`],6:[`Gospel`,`The four canons of the Bible, describing the life and works of Jesus Christ.`],7:[`St. John`,`One of the four authors of the New Testament, disciple of Jesus Christ.`],8:[`Scripture`,`Sacred writings of a religion, here The Holy Bible.`],9:[`slum dwellers`,`People who live in economically backward settlements.`],10:[`Chastity`,`Purity.`],11:[`Convent`,`A religious institution where nuns live, dedicated to worship, prayer and service.`],12:[`passion of Christ`,`extreme suffering of Christ during the crucifixion.`],13:[`Christmas`,`25th of December, celebrated as the birth of Jesus Christ.`],14:[`Nobel Peace Prize`,`International award given annually to individuals or organizations for significant contributions to peace.`]};
// word: [IPA, part of speech, English meaning, Bengali, Bengali pronunciation, example]
const DICT={peace:[`/piːs/`,`noun`,`freedom from war; calm and quiet`,`শান্তি`,`পিস`,`Everyone wants peace.`],
compassion:[`/kəmˈpæʃən/`,`noun`,`sympathy and concern for someone who is suffering`,`সহানুভূতি / দয়া`,`কমপ্যাশন`,`She showed compassion to the sick.`],
hunger:[`/ˈhʌŋɡə/`,`noun`,`the need or desire for food`,`ক্ষুধা`,`হাঙ্গার`,`Hunger made the children weak.`],
neglect:[`/nɪˈɡlekt/`,`noun`,`failure to care for someone`,`অবহেলা`,`নিগ্লেক্ট`,`Old people suffer from neglect.`],
forgotten:[`/fəˈɡɒtn/`,`adjective`,`no longer remembered`,`বিস্মৃত`,`ফরগটন`,`The parents felt forgotten.`],
gathered:[`/ˈɡæðəd/`,`verb`,`came together`,`সমবেত হয়েছিল`,`গ্যাদার্ড`,`We gathered in the hall.`],
composed:[`/kəmˈpəʊzd/`,`verb`,`wrote or created`,`রচনা করেছিলেন`,`কমপোজ্ড`,`He composed a prayer.`],
leapt:[`/lept/`,`verb`,`jumped suddenly`,`লাফিয়ে উঠল`,`লেপ্ট`,`The child leapt with joy.`],
proclaimed:[`/prəˈkleɪmd/`,`verb`,`announced publicly`,`ঘোষণা করেছিলেন`,`প্রোক্লেইম্ড`,`He proclaimed the news.`]};
