const BN={
'84_0':`যিশু যেমন আমাদের ভালোবেসেছেন, আমাদেরও পরস্পরকে তেমন ভালোবাসতে হবে — কষ্ট হওয়া পর্যন্ত। যে ঈশ্বরকে ভালোবাসে অথচ প্রতিবেশীকে ভালোবাসে না, সে মিথ্যাবাদী। ক্ষুধার্ত, গৃহহীন, একা মানুষের মধ্যেই ভালোবাসার ক্ষুধা; তা আমাদের নিজের ঘরেও থাকতে পারে। (ধর্মীয় বিশ্বাস)`,
'84_1':`একটি বৃদ্ধাশ্রমে সব আরাম থাকলেও বৃদ্ধরা দরজার দিকে তাকিয়ে সন্তানের অপেক্ষা করছিলেন, কেউ হাসছিলেন না। এটাই ঘরের ভেতরের দারিদ্র্য — ভালোবাসার অভাব।`,
'85_0':`পশ্চিমে পরিবারে কেউ না থাকায় তরুণরা নেশায় জড়াচ্ছে। তিনি গর্ভপাতকে শান্তির সবচেয়ে বড় শত্রু মনে করেন এবং দত্তক ও প্রাকৃতিক পরিবার পরিকল্পনার কথা বলেন। (এটি তাঁর নৈতিক ও ধর্মীয় মত)`,
'86_0':`তিনি দাবি করেন, কলকাতার গরিব পরিবারগুলি আত্মসংযমের পথে জন্ম নিয়ন্ত্রণ করে সুস্থ ও ঐক্যবদ্ধ থেকেছে। (তাঁর নিজের বিবরণ)`,
'86_1':`গরিবরা মহান মানুষ। রাস্তা থেকে তোলা এক মহিলা মৃত্যুর আগে হেসে শুধু "ধন্যবাদ" বললেন।`,
'86_2':`মহিলাটি কিছু চাননি, শুধু কৃতজ্ঞ ভালোবাসা দিয়েছেন। নর্দমা থেকে তোলা পুরুষটি বললেন, পশুর মতো বাঁচলেও তিনি দেবদূতের মতো মরবেন — কাউকে দোষ না দিয়ে।`,
'87_0':`তাঁরা নিজেদের সমাজকর্মী নয়, ঈশ্বরের ধ্যানে নিবেদিত মনে করেন। পরিবারে একসঙ্গে প্রার্থনা ও ভালোবাসাই অস্ত্রের চেয়ে বড় শান্তির পথ।`,
'87_1':`ভালোবাসা ঘর থেকে শুরু হয়। কাজ কতটা বড়, তা নয়; কতটা ভালোবাসা দিয়ে করা হলো, সেটাই আসল।`,
'87_2':`চিনির অভাবের সময় চার বছরের হিন্দু ছেলেটি তিন দিন চিনি না খেয়ে তা মাদারের শিশুদের জন্য দিল — ভালোবাসা ভাগ করে নেওয়ার উদাহরণ।`,
'87_3':`তিনি নরওয়ের ভালোবাসায় অভিভূত; নিজেকে ঘরে আছেন বলে মনে করছেন।`,
'87_4':`তিনি শ্রোতাদের বলেন, প্রথমে নিজের ঘর ও প্রতিবেশীর মধ্যে গরিবকে খুঁজতে। আটটি সন্তানের এক হিন্দু পরিবারের কথা বলতে শুরু করেন।`,
'88_0':`ক্ষুধার্ত পরিবারের মা চাল ভাগ করে প্রতিবেশী মুসলিম পরিবারকে দিলেন কারণ "ওরাও ক্ষুধার্ত"। মাদার আর চাল আনেননি যাতে তারা ভাগ করার আনন্দ পায়।`,
'88_1':`শ্রোতারা কষ্ট করে দান করেছেন। পুরস্কারের অর্থে তিনি গৃহহীনদের জন্য ঘর বানাবেন, কারণ ভালোবাসা ঘর থেকে শুরু হয়।`,
'88_2':`কাজের জীবন প্রার্থনায় বোনা থাকা চাই। পশ্চিমের দারিদ্র্য — অবাঞ্ছিত বোধ করা — দূর করা কঠিনতর, কারণ ভাতে ক্ষুধা মেটে, একাকিত্ব মেটে না।`,
'89_0':`যে মানুষ সমাজে বর্জিত ও অবাঞ্ছিত, তার দারিদ্র্য গভীর। ঘরে ঘরে হাসাই ভালোবাসার শুরু।`,
'89_1':`হাসি ভালোবাসার সূচনা। তিনি চান শ্রোতারা প্রার্থনা করুন এবং "কষ্ট না হওয়া পর্যন্ত" দান করুন।`,
'89_2':`বিছানায় পড়ে থাকা এক ব্যক্তি এক সপ্তাহ ধূমপান ছেড়ে ১৫ ডলার পাঠিয়েছিলেন — ত্যাগের উদাহরণ। শেষে তিনি বলেন: কোনো শিশু যেন অবাঞ্ছিত না থাকে এবং কঠিন সময়েও হাসি।`,
'90_0':`অধ্যাপকদের তিনি বলেন, পরিবারে পরস্পরের দিকে হাসো ও সময় দাও। ছোট কাজে বড় ভালোবাসা দিলে নরওয়ে "ভালোবাসার নীড়" হবে। তিনি "ঈশ্বর আশীর্বাদ করুন" বলে শেষ করেন।`,
'90_1':`সেন্ট ফ্রান্সিসের প্রার্থনার প্রথম অংশ: ঘৃণার স্থানে ভালোবাসা, অপরাধের স্থানে ক্ষমা, বিভেদের স্থানে ঐক্য, ভুলের স্থানে সত্য, সন্দেহের স্থানে বিশ্বাস।`,
'91_0':`প্রার্থনার শেষ: হতাশায় আশা, অন্ধকারে আলো, দুঃখে আনন্দ। নিজে সান্ত্বনা পাওয়ার চেয়ে সান্ত্বনা দেওয়াই শ্রেয়; দানেই পাওয়া হয়, ক্ষমাতেই ক্ষমা মেলে।`};
PAGES.forEach(p=>p.paras.forEach((q,j)=>{const b=BN[p.n+'_'+j];if(b){q.bn=b;q.k=q.k||'Summary in Bengali'}}));
Object.assign(DICT,{
lonely:[`/ˈləʊnli/`,`adjective`,`sad because you are alone`,`একাকী`,`লোনলি`,`The old man felt lonely.`],
institution:[`/ˌɪnstɪˈtjuːʃn/`,`noun`,`an organisation or home for care`,`প্রতিষ্ঠান`,`ইনস্টিটিউশন`,`They were placed in an institution.`],
sacrifice:[`/ˈsækrɪfaɪs/`,`noun`,`giving up something for others`,`ত্যাগ`,`স্যাক্রিফাইস`,`It was a great sacrifice.`],
abundance:[`/əˈbʌndəns/`,`noun`,`a large quantity; more than enough`,`প্রাচুর্য`,`অ্যাবান্ডান্স`,`Give not from abundance.`],
neighbour:[`/ˈneɪbə/`,`noun`,`a person living next door`,`প্রতিবেশী`,`নেইবার`,`Love your neighbour.`],
tenderness:[`/ˈtendənəs/`,`noun`,`gentle kindness`,`কোমলতা`,`টেন্ডারনেস`,`Children need tenderness.`],
radiating:[`/ˈreɪdieɪtɪŋ/`,`verb`,`shining out; spreading`,`বিকিরণ করছে`,`রেডিয়েটিং`,`The children were radiating joy.`],
conscience:[`/ˈkɒnʃəns/`,`noun`,`inner sense of right and wrong`,`বিবেক`,`কনশেন্স`,`She examined her conscience.`],
grateful:[`/ˈɡreɪtfl/`,`adjective`,`thankful`,`কৃতজ্ঞ`,`গ্রেটফুল`,`He was grateful for help.`],
abstaining:[`/əbˈsteɪnɪŋ/`,`verb`,`keeping away from something`,`বিরত থাকা`,`অ্যাবস্টেনিং`,`Abstaining needs self-control.`],
leper:[`/ˈlepə/`,`noun`,`a person suffering from leprosy`,`কুষ্ঠরোগী`,`লেপার`,`He cared for a leper.`],
naked:[`/ˈneɪkɪd/`,`adjective`,`without clothes`,`বস্ত্রহীন`,`নেকেড`,`A naked man lay in the street.`],
unwanted:[`/ʌnˈwɒntɪd/`,`adjective`,`not wanted or loved`,`অবাঞ্ছিত`,`আনওয়ান্টেড`,`No child should be unwanted.`],
smile:[`/smaɪl/`,`noun`,`a happy look on the face`,`হাসি`,`স্মাইল`,`A smile is the beginning of love.`],
sharing:[`/ˈʃeərɪŋ/`,`noun`,`giving part of what you have`,`ভাগ করে নেওয়া`,`শেয়ারিং`,`Sharing brings joy.`],
dying:[`/ˈdaɪɪŋ/`,`adjective`,`about to die`,`মুমূর্ষু`,`ডাইইং`,`She cared for the dying.`],
chastity:[`/ˈtʃæstəti/`,`noun`,`purity; self-denial`,`ব্রহ্মচর্য / পবিত্রতা`,`চ্যাস্টিটি`,`The nuns vowed chastity.`],
destroyer:[`/dɪˈstrɔɪə/`,`noun`,`one who destroys`,`ধ্বংসকারী`,`ডিস্ট্রয়ার`,`War is a destroyer of peace.`],
pardon:[`/ˈpɑːdn/`,`noun`,`forgiveness`,`ক্ষমা`,`পার্ডন`,`Let me bring pardon.`],
discord:[`/ˈdɪskɔːd/`,`noun`,`disagreement`,`বিরোধ`,`ডিসকর্ড`,`Bring union where there is discord.`]});
QA.push(
{q:'Why did the residents of the old age home look towards the door?',m:2,a:`They hoped a son or daughter would come to visit them.`,bn:`তাঁরা আশা করছিলেন সন্তান দেখা করতে আসবে।`,k:'hope; forgotten parents'},
{q:'Who was the "first messenger of peace" according to the speaker?',m:2,a:`The unborn child in Elizabeth's womb, who leapt with joy when Mary arrived — a religious image in the speaker's account.`,bn:`এলিজাবেথের গর্ভের অনাগত শিশু, যে মেরির আগমনে আনন্দে লাফিয়ে উঠেছিল।`,k:'Elizabeth; religious viewpoint'},
{q:'What does the speaker mean by "give until it hurts"?',m:2,a:`True giving involves sacrifice, not just giving from one's surplus.`,bn:`প্রকৃত দান মানে নিজের কষ্ট স্বীকার করে দান, উদ্বৃত্ত থেকে নয়।`,k:'sacrifice; abundance'},
{q:'How did the man who could only move his right hand help?',m:2,a:`He gave up smoking for a week and sent 15 dollars, which bought bread for hungry people.`,bn:`এক সপ্তাহ ধূমপান ছেড়ে ১৫ ডলার পাঠিয়েছিলেন, যা দিয়ে ক্ষুধার্তদের রুটি কেনা হয়।`,k:'sacrifice; sharing'},
{q:'What advice did she give the American professors?',m:2,a:`She told them to smile at each other and make time for each other in the family.`,bn:`তিনি বলেছিলেন, পরিবারে পরস্পরের দিকে হাসো ও সময় দাও।`,k:'smile; family'},
{q:'Why does she say the Sisters are "contemplatives in the heart of the world"?',m:2,a:`She believes that serving the poor is touching Christ's body, so their work is prayer — her religious viewpoint.`,bn:`তিনি মনে করেন গরিবের সেবা মানেই ঈশ্বরের সেবা, তাই কাজই প্রার্থনা।`,k:'service; prayer'},
{q:'Contrast material poverty and emotional poverty in the lecture. (Broad)',m:6,a:`Introduction: she distinguishes hunger for food from hunger for love. Main points: rice satisfies the hungry street person; those who feel unwanted and shut out suffer a deeper poverty. Incidents: the old-age home, lonely Western youth. Analysis: she finds Western poverty harder to remove. Conclusion: care requires attention, not just material help.`,bn:`ভাত দিলে ক্ষুধা মেটে, কিন্তু অবাঞ্ছিত বোধ করা মানুষের একাকিত্ব মেটে না; তাই মানসিক দারিদ্র্য দূর করা কঠিনতর।`,k:'rice; unwanted; old-age home'});
